"""
Synthesizer Agent: Generates a well-structured Markdown research report
with verified claims, key findings, and auditable references.
"""

import re
from typing import Any, Dict, List
from backend.app.services.llm_service import chat


def synthesize_report(
    topic: str,
    claims: List[Dict[str, Any]],
    sources: List[Dict[str, str]],
) -> str:
    """
    Synthesize research findings into a structured Markdown document.

    Required structure only:
    - # Research Report: <topic> (Title)
    - ## Executive Summary (max ~150 words)
    - ## Key Findings (one bullet per claim, max 6)
    - ## Evaluated Claims & Verification Audit
    - ## References

    Args:
        topic: The research topic investigated.
        claims: Verified claims list from the Fact Checker agent.
        sources: Consulted sources list (capped at 12).

    Returns:
        A complete Markdown formatted research report.
    """
    valid_sources = [s for s in sources if s.get("url")]
    valid_urls = {s["url"] for s in valid_sources}
    source_by_url = {s["url"]: s for s in valid_sources if s.get("url")}

    # Calculate support ratio across all evaluated claims
    supported_count = sum(1 for c in claims if c.get("status") == "supported")
    total_claims = len(claims)

    # Format substantiated claims only (unsupported claims must NOT appear in findings/summary)
    substantiated_claims = [c for c in claims if c.get("status") in ("supported", "single_source")]
    claims_descriptions = []

    for c in substantiated_claims:
        st = c.get("status")
        stmt = c.get("statement", "")
        if st == "supported":
            claims_descriptions.append(f"- [Corroborated by multiple independent sources]: {stmt}")
        elif st == "single_source":
            claims_descriptions.append(f"- [Reported by only one source]: {stmt}")

    claims_text = "\n".join(claims_descriptions) if claims_descriptions else "- No substantiated claims available."
    sources_summary = "\n".join(
        f"- {s.get('title') or s.get('url')}: {(s.get('content') or '')[:250]}..."
        for s in valid_sources[:6]
    )

    half_supported = (supported_count >= (total_claims / 2)) if total_claims > 0 else False
    evidence_constraint = (
        "CRITICAL: Fewer than half of the evaluated claims are supported by multiple sources. "
        "The Executive Summary MUST explicitly state that evidence on this topic is limited."
        if not half_supported else ""
    )

    system_prompt = (
        "You are an objective technical research writer. Synthesize the provided evaluated claims into a concise report.\n"
        "Strict rules:\n"
        "1. Write ONLY the following two sections in markdown:\n"
        "   ## Executive Summary\n"
        "   (Max ~150 words. Objective, grounded strictly in the provided substantiated claims. Unsupported claims must NOT appear.)\n\n"
        "   ## Key Findings\n"
        "   (Bulleted list with one bullet per substantiated claim, maximum 6 bullets. Unsupported claims must NOT appear.)\n"
        "2. Wording rules:\n"
        "   - The words 'verified', 'confirmed', 'established', or 'well-documented' may ONLY be used for claims marked [Corroborated by multiple independent sources].\n"
        "   - For claims marked [Reported by only one source], use cautious attribution such as 'reported by one source' or 'according to preliminary reports'. Never describe them as verified.\n"
        "   - Claims with status 'unsupported' must NOT appear in Key Findings or the Executive Summary.\n"
        f"   {evidence_constraint}\n"
        "3. No filler, comparison tables, or placeholders:\n"
        "   - Do NOT add statements not backed by a claim or source.\n"
        "   - Forbid placeholders such as '(implicit in source contexts)'.\n"
        "   - Do NOT include comparison tables, conclusion sections, or status tags in prose (never write 【...】 or [SUPPORTED] in the body).\n"
        "4. Do NOT output the document title (# Research Report), the Claims Audit section, or References (they are added automatically)."
    )

    user_prompt = (
        f"Research Topic: {topic}\n\n"
        f"Evaluated Substantiated Claims (Unsupported claims excluded):\n{claims_text}\n\n"
        f"Source Contexts:\n{sources_summary}\n\n"
        "Compose the Executive Summary and Key Findings according to the rules above."
    )

    raw_narrative = chat(system=system_prompt, user=user_prompt, temperature=0.1)

    # Post-processing: strip any leaked status tags like 【...】 or [SUPPORTED] or [SINGLE_SOURCE]
    narrative_cleaned = re.sub(r"【.*?】", "", raw_narrative)
    narrative_cleaned = re.sub(r"\[(SUPPORTED|SINGLE_SOURCE|UNSUPPORTED)\]", "", narrative_cleaned, flags=re.IGNORECASE)
    # Strip any redundant top-level # Research Report header if generated by LLM
    narrative_cleaned = re.sub(r"^#\s+Research Report[^\n]*\n*", "", narrative_cleaned.strip(), flags=re.IGNORECASE).strip()

    # Collect cited URLs in order of appearance across substantiated claims
    cited_urls: List[str] = []
    for c in claims:
        if c.get("status") not in ("supported", "single_source"):
            continue
        c_urls = [u for u in c.get("source_urls", []) if u in valid_urls]
        if not c_urls and c.get("source_url") and c.get("source_url") in valid_urls:
            c_urls = [c["source_url"]]
        for u in c_urls:
            if u not in cited_urls:
                cited_urls.append(u)

    url_to_source_num = {u: idx for idx, u in enumerate(cited_urls, 1)}

    # Format the definitive Markdown report with strictly required sections
    lines: List[str] = [
        f"# Research Report: {topic}",
        "",
        narrative_cleaned,
        "",
        "## Evaluated Claims & Verification Audit",
        "",
    ]

    if claims:
        for c in claims:
            status = c.get("status")
            if status == "supported":
                status_tag = "✓ Verified"
            elif status == "single_source":
                status_tag = "⚠ Single source"
            else:
                status_tag = "✗ Unsupported"

            # Resolve citation URLs strictly from valid_sources
            urls = [u for u in c.get("source_urls", []) if u in valid_urls]
            if not urls and c.get("source_url") and c.get("source_url") in valid_urls:
                urls = [c["source_url"]]

            if urls and status != "unsupported":
                links = [
                    f"[Source {url_to_source_num[u]}]({u})"
                    for u in urls
                    if u in url_to_source_num
                ]
                citation = f"({', '.join(links)})" if links else "(No direct citation)"
            else:
                citation = "(No direct citation)"

            lines.append(f"- **{status_tag}**: {c.get('statement')} {citation}")
    else:
        lines.append("- No specific claims evaluated.")

    lines.extend([
        "",
        "## References",
        "",
    ])

    if cited_urls:
        for idx, u in enumerate(cited_urls, 1):
            s = source_by_url.get(u, {})
            title = s.get("title") or u
            lines.append(f"{idx}. [{title}]({u})")
    else:
        lines.append("- No external sources cited.")

    return "\n".join(lines)
